<?php
    include 'bd.php';
    $id = $_GET['id'];
    $sql = "SELECT * FROM ventas WHERE id = $id";
    $resultado = mysqli_query($conexion, $sql);
    $row = mysqli_fetch_assoc($resultado);
    $sede = $row['sede'];
    $vendedor = $row['vendedor'];
    $mozo = $row['mozo'];
    $fechaEmision = $row['fechaEmision'];
    $horaEmision = $row['horaEmision'];
    $nComprobante = $row['nComprobante'];
    $tipoComprobante = $row['tipoComprobante'];
    $nombres = $row['nombres'];
    $apellidos = $row['apellidos'];
    $dni = $row['dni'];
    $celular = $row['celular'];
    $subtotal = $row['subtotal'];
    $igv = $row['igv'];
    $bolsas = $row['bolsas'];
    $pagocon = $row['pagocon'];
    $vuelto = $row['vuelto'];
    $total = $row['total'];
    $ruc = $row['ruc'];
    $razonSocial = $row['razonSocial'];
    $direccion = $row['direccionFiscal'];
    $sqlb = "SELECT * FROM detalleventas WHERE idVenta = $id";
    $resultadob = mysqli_query($conexion, $sqlb);
    $rowb = mysqli_fetch_assoc($resultadob);

    require "./code128.php";
    $pdf = new PDF_Code128('P','mm',array(80,258));
    $pdf->SetMargins(4,10,4);
    $pdf->AddPage();
    $pdf->SetFont('Arial','B',10);
    $pdf->SetTextColor(0,0,0);
    $pdf->MultiCell(0,5,utf8_decode(strtoupper("La Frutalina")),0,'C',false);
    $pdf->SetFont('Arial','',9);
    $pdf->MultiCell(0,5,utf8_decode($sede),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Lima - Cañete - San Vicente"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("RUC: 10101397608"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("De: Ruiz Ojeda Ivone Guisela"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Celular: 961229039"),0,'C',false);
    $pdf->Ln(1);
    $pdf->Cell(0,5,utf8_decode("-------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $nuevoComprobanteB = "";
    if($tipoComprobante == "Boleta"){
        $nuevoComprobanteB = "Boleta";
    }else{
        $nuevoComprobantB = "Factura";
    }
    $pdf->MultiCell(0,5,utf8_decode($nuevoComprobanteB." electrónica: $nComprobante"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Cajero: $vendedor"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Fecha y hora de emisión: ".date("d/m/Y", strtotime($fechaEmision))." ".$horaEmision),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Mozo: $mozo"),0,'C',false);
    $pdf->SetFont('Arial','',9);
    $pdf->Ln(1);
    $pdf->Cell(0,5,utf8_decode("-------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $pdf->MultiCell(0,5,utf8_decode("Cliente: $nombres $apellidos"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Documento: $dni"),0,'C',false);
    $pdf->MultiCell(0,5,utf8_decode("Celular: $celular"),0,'C',false);
    if($tipoComprobante == "Factura") {
        $pdf->MultiCell(0,5,utf8_decode("RUC: $ruc"),0,'C',false);
        $pdf->MultiCell(0,5,utf8_decode("Razón social: $razonSocial"),0,'C',false);
        $pdf->MultiCell(0,5,utf8_decode("Dirección fiscal: $direccion"),0,'C',false);
    }
    $pdf->Ln(1);
    $pdf->Cell(0,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(3);
    $pdf->Cell(10,5,utf8_decode("Cant."),0,0,'C');
    $pdf->Cell(31,5,utf8_decode("Producto"),0,0,'C');
    $pdf->Cell(15,5,utf8_decode("Precio"),0,0,'C');
    $pdf->Cell(15,5,utf8_decode("Total"),0,0,'C');
    $pdf->Ln(3);
    $pdf->Cell(72,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(3);
    foreach ($resultadob as $rowb) {
        $pdf->Cell(10,4,utf8_decode($rowb['cantidad']),0,0,'C');
        $pdf->Cell(31,4,utf8_decode($rowb['nombre']),0,0,'C');
        $pdf->Cell(15,4,utf8_decode("S/".$rowb['precio']),0,0,'C');
        $pdf->Cell(15,4,utf8_decode("S/".$rowb['total']),0,0,'C');
        $pdf->Ln(4);
    }
    $pdf->Cell(72,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Descuento"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode("S/0.00"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("OP. Gravadas"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode("S/0.00"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("OP. Exoneradas"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode("S/0.00"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("IGV(18%)"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode("S/".$igv),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Bolsas"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode($bolsas),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Subtotal"),0,0,'L');
    $pdf->Cell(32,5,utf8_decode("S/".$subtotal),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(72,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Pago con:"),0,0,'C');
    $pdf->Cell(32,5,utf8_decode($pagocon),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Vuelto:"),0,0,'C');
    $pdf->Cell(32,5,utf8_decode($vuelto),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(72,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $pdf->Cell(18,5,utf8_decode(""),0,0,'C');
    $pdf->Cell(22,5,utf8_decode("Total a pagar"),0,0,'C');
    $pdf->Cell(32,5,utf8_decode("S/".$total),0,0,'C');
    $pdf->Ln(5);
    require_once "CifrasEnLetras.php";
    $v = new CifrasEnLetras(); 
    $letra=($v->convertirEurosEnLetras(floatval($total)));
    $pdf->Cell(72,5,utf8_decode("Son: ".$letra),0,0,'L');
    $pdf->Ln(5);
    $pdf->Cell(72,5,utf8_decode("-------------------------------------------------------------------"),0,0,'C');
    $pdf->Ln(5);
    $nuevoComprobante = "";
    if($tipoComprobante == "Boleta"){
        $nuevoComprobante = "boleta";
    }else{
        $nuevoComprobante = "factura";
    }
    $pdf->MultiCell(0,5,utf8_decode("Representación impresa de la ".$nuevoComprobante." de venta electrónica desarrollada y elaborada por el Semillero CañeteL@b de la UNDC"),0,'C',false);
    $pdf->SetFont('Arial','B',9);
    $pdf->Cell(0,7,utf8_decode("Gracias por su compra"),'',0,'C');
    $pdf->Ln(9);
    $pdf->Code128(5,$pdf->GetY(),$nComprobante,70,20);
    $pdf->SetXY(0,$pdf->GetY()+21);
    $pdf->SetFont('Arial','',14);
    $pdf->MultiCell(0,5,utf8_decode($nComprobante),0,'C',false);
    $pdf->Output("I","Comprobante.$id.pdf",true);